services:
  rng-api:
    image: labs/rng-api:21.05
    environment:
      - Logging__LogLevel__Default=Debug
    networks:
      - app-net

  rng-web:
    image: labs/rng-web:21.05
    environment:
      - Logging__LogLevel__Default=Debug
      - RngApi__Url=http://rng-api/rng
    ports:
      - "8090:80"
    networks:
      - app-net

networks:
  app-net:
